import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ChevronDown, CircleHelp, Info, Lock, LogOut, Bell } from 'lucide-react'
import { saveProfile, session } from '../../services'
import { enablePushNotifications } from '../../push'
import { label, type User } from '../../domain'
import { Input, Page } from '../../shared/ui'
import { logo } from '../../shared/assets'
import type { Toast } from '../../shared/types'
import { PasswordDialog } from '../auth/PasswordDialog'

export function ProfilePage({user,setUser,setToast}:{user:User;setUser:(u:User)=>void;setToast:(t:Toast)=>void}){const nav=useNavigate();const[name,setName]=useState(user.name);const[contact,setContact]=useState(user.contact||'');const[address,setAddress]=useState(user.address||'');const[password,setPassword]=useState(false);const save=async(e:FormEvent)=>{e.preventDefault();const next={...user,name,contact,address};await saveProfile(next);setUser(next);setToast({message:'Profile updated successfully.'})};const enableAlerts=async()=>{const outcome=await enablePushNotifications();setToast(outcome.ok?{message:'Push notifications enabled. You will be alerted about official broadcasts and SOS activity.'}:{message:outcome.reason,kind:'error'})};return <Page title="Profile" eyebrow="USER NODE"><div className="profile-hero"><img src={user.profileImageUrl||logo} alt={`${user.name}'s profile photo`}/><h2>{user.name}</h2><p>{label(user.role)} · {user.email}</p></div><form className="form" onSubmit={save}><Input label="Full Name" value={name} onChange={setName}/><Input label="Contact Number" value={contact} onChange={setContact}/><Input label="Physical Location / Address" value={address} onChange={setAddress}/><button className="primary-button">SAVE PROFILE</button></form><div className="settings-list"><button onClick={()=>setPassword(true)}><Lock/> Change Password <ChevronDown/></button><button onClick={enableAlerts}><Bell/> Enable Push Notifications <ChevronDown/></button><Link to="/about"><Info/> About TraceNet <ChevronDown/></Link><button onClick={()=>setToast({message:'Your help message can be submitted from the support center.'})}><CircleHelp/> Help &amp; Support <ChevronDown/></button><button className="danger-text" onClick={async()=>{await session.logout();nav('/welcome')}}><LogOut/> Log Out</button></div>{password&&<PasswordDialog close={()=>setPassword(false)} setToast={setToast}/>}</Page>}
