import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { LoaderCircle } from 'lucide-react'
import { authErrorMessage, saveProfile, session, uploadSingle } from '../../services'
import { type Role, type User } from '../../domain'
import { Brand, FileInput, Input, Select } from '../../shared/ui'
import { logo } from '../../shared/assets'
import type { Toast } from '../../shared/types'

export function SignUpPage({setToast}:{setToast:(t:Toast)=>void}){const nav=useNavigate();const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[role,setRole]=useState<Role>('CITIZEN');const[badge,setBadge]=useState('');const[contact,setContact]=useState('');const[address,setAddress]=useState('');const[idCard,setIdCard]=useState<File>();const[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();if(!name||!email||!password||role==='LAW_ENFORCER'&&(!badge||!contact||!address||!idCard)){setToast({message:'Please complete all required registration details.',kind:'error'});return}setBusy(true);try{const r=await session.signUp(email,password);let idCardUrl:string|undefined;if(idCard)idCardUrl=await uploadSingle(idCard,`id_cards/${r.user.uid}/${idCard.name}`);const user:User={id:r.user.uid,name,email,role:role==='ADMIN'?'CITIZEN':role,isApproved:role==='CITIZEN'||role==='ADMIN',badgeNumber:badge,contact,address,profileImageUrl:undefined};await saveProfile({...user,...(idCardUrl?{idCardUrl}: {})} as User);setToast({message:role==='LAW_ENFORCER'?'Deployment request submitted. Stand by for verification.':'Account created successfully.'});nav('/')}catch(err){setToast({message:authErrorMessage(err,'Registration failed'),kind:'error'})}finally{setBusy(false)}};return <main className="auth-page signup"><img className="auth-logo" src={logo}/><Brand/><h1>CREATE ACCOUNT</h1><form className="auth-form" onSubmit={submit}><Input label="Full Name" value={name} onChange={setName}/><Input label="Email Address" value={email} onChange={setEmail} type="email"/><Input label="Password" value={password} onChange={setPassword} type="password"/><Select label="Access Level" value={role} onChange={v=>setRole(v as Role)} options={['CITIZEN','LAW_ENFORCER','ADMIN']}/><Input label="Physical Location / Address" value={address} onChange={setAddress}/>{role==='LAW_ENFORCER'&&<><h3>ENFORCER VERIFICATION</h3><Input label="Badge Number" value={badge} onChange={setBadge}/><Input label="Contact Number" value={contact} onChange={setContact}/><FileInput label="Tap to upload ID Card Image" accept="image/*" onFile={setIdCard}/></>}<button className="outline-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:'SIGN UP'}</button><p className="terms">By signing up, you agree to our <b>Terms</b> &amp; <b>Privacy</b></p><Link className="auth-link" to="/sign-in">Already have an account? Sign In</Link></form></main>}
