import { useState } from 'react'
import { Edit3, Trash2 } from 'lucide-react'
import { write } from '../../services'
import { label, type Report } from '../../domain'
import { MediaThumb } from '../../components/MediaAsset'
import { Dialog } from '../ui'
import type { Toast } from '../types'

export function ReportCard({report,setToast}:{report:Report;setToast?:(t:Toast)=>void}){const[edit,setEdit]=useState(false);const hasMedia=report.imageUrls.length>0||report.videoUrls.length>0||report.audioUrls.length>0;return <article className="record-card"><span className={`status ${report.status.toLowerCase()}`}>{label(report.status)}</span><h3>{report.title}</h3><p>{report.description}</p><small>{label(report.type)} · {report.county||'Liberia'}</small>{hasMedia&&<div className="thumbs">{report.imageUrls.map(u=><MediaThumb key={u} url={u} kind="image" alt={`Photo evidence for ${report.title}`}/>)}{report.videoUrls.map(u=><MediaThumb key={u} url={u} kind="video" alt={`Video evidence for ${report.title}`}/>)}</div>}{report.audioUrls.map(u=><MediaThumb key={u} url={u} kind="audio" alt={`Audio evidence for ${report.title}`}/>)}{setToast&&<div className="card-actions"><button onClick={()=>setEdit(true)}><Edit3/> Edit</button><button onClick={async()=>{await write('reports',{...report,isDeleted:true,updatedAt:Date.now()});setToast({message:'Report moved to deleted records.'})}}><Trash2/> Delete</button></div>}{edit&&<Dialog title="Edit Report" close={()=>setEdit(false)}><form className="form" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);await write('reports',{...report,title:String(form.get('title')),description:String(form.get('description')),updatedAt:Date.now()});setToast?.({message:'Report updated'});setEdit(false)}}><label className="input"><span>Title</span><input name="title" defaultValue={report.title}/></label><label className="input"><span>Description</span><textarea name="description" defaultValue={report.description}/></label><button className="primary-button">SAVE</button></form></Dialog>}</article>}
