import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { LoaderCircle } from 'lucide-react'
import { submitReportWithMedia } from '../../services'
import { uuid } from '../../domain'
import { FileInput, Input, Page, Select, TextArea } from '../../shared/ui'
import { CaptureButtons } from '../../shared/CaptureButtons'
import type { Toast } from '../../shared/types'

export function WantedForm({setToast}:{setToast:(t:Toast)=>void}){const nav=useNavigate();const[id]=useState(()=>uuid());const[name,setName]=useState('');const[description,setDescription]=useState('');const[lastSeen,setLastSeen]=useState('');const[reward,setReward]=useState('');const[category,setCategory]=useState('Wanted person notices');const[files,setFiles]=useState<File[]>([]);const[busy,setBusy]=useState(false);const addFiles=(incoming:File[])=>setFiles(v=>[...v,...incoming].slice(0,4));const submit=async(e:FormEvent)=>{e.preventDefault();if(!name||!description){setToast({message:'Name and information are required.',kind:'error'});return}setBusy(true);try{const{status}=await submitReportWithMedia({collection:'wanted_criminals',reportId:id,storagePath:`criminals/${id}`,files,payload:{name,description,lastSeen,reward,isArrested:false,timestamp:Date.now(),updatedAt:Date.now(),category,status:'SUBMITTED',isVerified:false}});if(status==='SYNCED')setToast({message:'Wanted criminal notice submitted for verification.'});else if(status==='FAILED'||status==='CONFLICT')setToast({message:'Notice saved on this device but could not sync yet. It will retry automatically.',kind:'error'});else setToast({message:'You appear to be offline. The notice is saved on this device and will upload once you reconnect.'});nav('/operations')}catch(err){setToast({message:err instanceof Error?err.message:'Unable to submit notice.',kind:'error'})}finally{setBusy(false)}};return <Page eyebrow="ADMIN NODE" title="POST WANTED CRIMINAL DATA"><form className="form" onSubmit={submit}><Input label="Criminal Name" value={name} onChange={setName}/><TextArea label="Information / Crimes" value={description} onChange={setDescription}/><Input label="Last Seen Location" value={lastSeen} onChange={setLastSeen}/><Input label="Reward (Optional)" value={reward} onChange={setReward}/><Select label="Category" value={category} onChange={setCategory} options={['Wanted person notices','Missing person','Public safety advisory']}/><FileInput label="CRIMINAL EVIDENCE / PHOTOS (UP TO 4)" accept="image/*" multiple onFiles={f=>addFiles(Array.from(f??[]))}/><CaptureButtons onFiles={addFiles} setToast={setToast} allow={['photo']}/><button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:'BROADCAST ALERT'}</button></form></Page>}
