export type Role = 'CITIZEN' | 'LAW_ENFORCER' | 'ADMIN'
export type Status = 'PENDING' | 'UNDER_INVESTIGATION' | 'VERIFIED' | 'RESOLVED' | 'DISMISSED' | 'FALSE_REPORT'
export type ReportType = 'MISSING_PERSON' | 'WANTED_INDIVIDUAL' | 'SUSPICIOUS_ACTIVITY' | 'CRIME_REPORT' | 'DRUGS_DEALER' | 'HIT_AND_RUN' | 'THEFT' | 'BURGLARY' | 'ARMED_ROBBERY' | 'KIDNAPPING' | 'FRAUD' | 'VANDALISM' | 'RAPE' | 'CAR_ACCIDENT' | 'SUICIDE' | 'DOMESTIC_VIOLENCE' | 'ASSAULT'
export const reportTypes: ReportType[] = ['MISSING_PERSON','WANTED_INDIVUAL' as ReportType,'SUSPICIOUS_ACTIVITY','CRIME_REPORT','DRUGS_DEALER','HIT_AND_RUN','THEFT','BURGLARY','ARMED_ROBBERY','KIDNAPPING','FRAUD','VANDALISM','RAPE','CAR_ACCIDENT','SUICIDE','DOMESTIC_VIOLENCE','ASSAULT']
export const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase())
export interface User { id:string; name:string; email:string; role:Role; isApproved:boolean; profileImageUrl?:string; badgeNumber?:string; contact?:string; address?:string; status?:string; reputationScore?:number }
export interface Report { id:string; title:string; description:string; type:ReportType; county?:string; latitude:number; longitude:number; timestamp:number; updatedAt:number; reporterId:string; isAnonymous:boolean; status:Status; imageUrls:string[]; videoUrls:string[]; audioUrls:string[]; incidentTimestamp:number; aiScreeningStatus:string; aiFlaggedReasons:string[]; internalNotes?:string; assignedInvestigator?:string; isEscalated?:boolean; contactInfo?:string; isDeleted?:boolean }
export interface Tip { id:string; reportId:string; content:string; isAnonymous:boolean; timestamp:number; submitterId?:string; isReviewed:boolean; aiScreeningStatus:string; aiFlaggedReasons:string[]; isDeleted?:boolean }
export interface Alert { id:string; title:string; content:string; urgency:number; locationName:string; county?:string; latitude:number; longitude:number; timestamp:number }
export interface Wanted { id:string; name:string; description:string; lastSeen:string; county?:string; reward?:string; imageUrls:string[]; isArrested:boolean; timestamp:number; updatedAt:number; category:string; status:string; isVerified:boolean; isDeleted?:boolean }
export const uuid = () => crypto.randomUUID()
export const screenContent = (text:string) => { const terms:[string,string][] = [['Abusive/Offensive Language','fuck|shit|bitch|asshole|bastard|idiot|stupid|dumb|jerk|crap|cunt|dick|abuse|abusive|harass'],['Direct/Indirect Threat','kill|die|shoot|attack|bomb|murder|harm|destroy|burn|assassinate|stab|threat'],['Hate Speech','slur|hate|scum|trash']]; const lower=text.toLowerCase(); const reasons=terms.filter(([,words])=>words.split('|').some(word=>lower.includes(word))).map(([reason])=>reason); if(text.trim() && text.trim().length<5) reasons.push('Suspiciously Short Content'); return {status:reasons.length?'FLAGGED':'CLEAN',reasons} }
